### PR TITLE
Merge in main and update uri parsing in timeseries factory

### PR DESCRIPTION
**Pull request by Cadair**

### CODE REVIEW

**Comment by Cadair** [comment]
Am I right in thinking this was just squashed merged? That's going to cause chaos with the commit history. Is there any chance you could add me as a collaborator on this repo so I can push to this branch?

I think the root of the problem is that you opened this PR from the main branch which means that contributors to sunpy can't push to the PR branch, which makes this a little easier.

**Comment by wmoapl** [comment]
Would it be easier if I merged #14 into its own branch on sunpy, and then you merge these subsequent PRs there? I think that would solve your permissions issue

**Comment by Cadair** [comment]
The problem with changing branches is that it will close the existing PR which isn't really what I want.

**Comment by Cadair** [comment]
If you can revert merging this then that will be a good start.

**Comment by wmoapl** [comment]
ok I reverted and add you to the org. Let me if you have access

**Comment by Cadair** [comment]
Yes, thanks!

**Pull request merged**
